const RootDatabaseFolder = "./admin/database";
const MatchsCSVHeader =
  "date;home_team_id;home_team_goals;away_team_goals;away_team_id;tournament_id";

module.exports = {
  RootDatabaseFolder,
  MatchsCSVHeader,
  TeamsPaths: [
    "/team/AME",
    "/team/ATG",
    "/team/ATH",
    "/team/ATL",
    "/team/AVA",
    "/team/BAH",
    "/team/BOT",
    "/team/CEA",
    "/team/CHA",
    "/team/COR",
    "/team/CTB",
    "/team/CRU",
    "/team/CSA",
    "/team/CUI",
    "/team/FLA",
    "/team/FLU",
    "/team/FOR",
    "/team/GOI",
    "/team/GRE",
    "/team/INT",
    "/team/JUV",
    "/team/PAL",
    "/team/PAR",
    "/team/RED",
    "/team/SAN",
    "/team/SAO",
    "/team/SPO",
    "/team/VAS",
    "/team/VIT",
  ],
  TeamsData: `${RootDatabaseFolder}/teams.csv`,
  TournamentsData: `${RootDatabaseFolder}/tournaments.csv`,
  MatchesFolder: `${RootDatabaseFolder}/matches`,
  TeamsRatingsFolder: `${RootDatabaseFolder}/ratings/teams`,
  RatingFolder: `${RootDatabaseFolder}/ratings`,
  RatingsData: `${RootDatabaseFolder}/ratings/ratings.csv`,
};
